# Generated by Django 4.1 on 2023-11-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="1998-10-10"),
            preserve_default=False,
        ),
    ]
